[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
mangadex-api-schema-rust = { version = "0.9.0", features = ["serialize"] }
reqwest = { version = "0.12.5", features = ["rustls-tls", "json"] }
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
tokio = { version = "1.39.2", features = ["full"] }
uuid = "1.10.0"
warp = "0.3.7"
